WITH source_summary AS (
    SELECT
        _id,
        time_stamp,
        ip,
        user_agent,
        resolution,
        user_id_db,
        device_id,
        api_version,
        store_id,
        local_time,
        show_recommendation,
        current_url,
        referrer_url,
        email_address,
        collection,
        currency,
        price,
        product_id,
        cat_id,
        collect_id,
        order_id,
        is_paypal,
        utm_source,
        utm_medium,
        option,
        cart_products,
        key_search,
        viewing_product_id,
        recommendation,
        recommendation_clicked_position,
        recommendation_product_id,
        recommendation_product_position
    FROM {{ source('glamira_raw', 'summary_raw') }}
    WHERE _id IS NOT NULL
    AND collection = 'checkout_success'
),

-- Unnest cart_products
cart_exploded AS (
    SELECT
        s._id,
        s.time_stamp,
        s.ip,
        s.user_agent,
        s.resolution,
        s.user_id_db,
        s.device_id,
        s.api_version,
        s.store_id,
        s.local_time,
        s.show_recommendation,
        s.current_url,
        s.referrer_url,
        s.email_address,
        s.collection,
        s.cat_id,
        s.collect_id,
        s.order_id,
        s.is_paypal,
        s.utm_source,
        s.utm_medium,
        s.option,
        s.key_search,
        s.viewing_product_id,
        s.recommendation,
        s.recommendation_clicked_position,
        s.recommendation_product_id,
        s.recommendation_product_position,

        COALESCE(cp.product_id, s.product_id)   AS product_id,
        COALESCE(cp.price,      s.price)         AS price,
        COALESCE(cp.currency,   s.currency)      AS currency,
        COALESCE(cp.amount,     1)               AS order_quantity,
        cp.option                                AS cart_product_options

    FROM source_summary s
    LEFT JOIN UNNEST(s.cart_products) AS cp
)

SELECT
    CAST(_id AS STRING)                                         AS event_id,
    CAST(order_id AS STRING)                                    AS order_id,
    CAST(user_id_db AS STRING)                                  AS customer_id,
    CAST(product_id AS STRING)                                  AS product_id,
    CAST(store_id AS STRING)                                    AS store_id,
    COALESCE(TRIM(CAST(device_id AS STRING)), 'unknown')        AS device_code,
    CAST(cat_id AS STRING)                                      AS category_id,
    CAST(collect_id AS STRING)                                  AS collection_id,
    TIMESTAMP_SECONDS(CAST(time_stamp AS INT64))                AS order_timestamp,
    DATE(TIMESTAMP_SECONDS(CAST(time_stamp AS INT64)))          AS actual_date,
    CAST(local_time AS STRING)                                  AS local_time,
    CAST(price AS NUMERIC)                                      AS price,
    CAST(order_quantity AS INT64)                               AS order_quantity,
    CAST(price AS NUMERIC) * CAST(order_quantity AS INT64)      AS line_total,
    CAST(currency AS STRING)                                    AS currency,
    CAST(ip AS STRING)                                          AS ip_address,
    CAST(user_agent AS STRING)                                  AS user_agent,
    COALESCE(TRIM(CAST(resolution AS STRING)), 'unknown')       AS resolution,
    CAST(api_version AS STRING)                                 AS api_version,
    CAST(email_address AS STRING)                               AS email_address,
    CAST(is_paypal AS BOOLEAN)                                  AS is_paypal,
    CAST(show_recommendation AS STRING)                         AS show_recommendation,
    CAST(current_url AS STRING)                                 AS current_url,
    CAST(referrer_url AS STRING)                                AS referrer_url,
    CAST(collection AS STRING)                                  AS collection_name,
    CAST(utm_source AS STRING)                                  AS utm_source,
    CAST(utm_medium AS STRING)                                  AS utm_medium,
    CAST(key_search AS STRING)                                  AS key_search,
    CAST(viewing_product_id AS STRING)                          AS viewing_product_id,
    CAST(recommendation AS STRING)                              AS recommendation,
    CAST(recommendation_clicked_position AS INT64)              AS recommendation_clicked_position,
    CAST(recommendation_product_id AS STRING)                   AS recommendation_product_id,
    CAST(recommendation_product_position AS INT64)              AS recommendation_product_position,
    TO_JSON_STRING(option)                                      AS product_options,
    TO_JSON_STRING(cart_product_options)                        AS cart_product_options

FROM cart_exploded